"""DDIM sampler for PXRD-Diff.

Generates crystal structures (fractional coords + lattice parameters)
from Gaussian noise, conditioned on a PXRD pattern and known atom types.

Uses DDIM (Song et al. 2020) for deterministic, few-step sampling.
At each denoising step, fractional coordinates are wrapped to [0, 1)
to stay on the torus.

Typical usage:
    sampler = DDIMSampler(encoder, denoiser, n_steps=50)
    coords, lattice_params = sampler.sample(pxrd, atom_types, lattice_init, mask)
"""
from __future__ import annotations

import torch
import torch.nn as nn

from pxrd_diff.diffusion import cosine_alpha_bar


class DDIMSampler:
    """DDIM reverse process for crystal structure generation.

    Args:
        encoder:   trained PXRDEncoder
        denoiser:  trained CrystalDenoiser
        n_steps:   number of DDIM denoising steps (fewer = faster, noisier)
        eta:       DDIM stochasticity (0 = deterministic, 1 = DDPM)
        lat_mean:  (6,) lattice param normalization mean
        lat_std:   (6,) lattice param normalization std
    """

    def __init__(self, encoder: nn.Module, denoiser: nn.Module,
                 n_steps: int = 50, eta: float = 0.0,
                 lat_mean: torch.Tensor | None = None,
                 lat_std: torch.Tensor | None = None):
        self.encoder = encoder
        self.denoiser = denoiser
        self.n_steps = n_steps
        self.eta = eta
        self.lat_mean = lat_mean
        self.lat_std = lat_std

    @torch.no_grad()
    def sample(self, pxrd: torch.Tensor, atom_types: torch.Tensor,
               lattice_init: torch.Tensor, mask: torch.Tensor,
               ) -> tuple[torch.Tensor, torch.Tensor]:
        """Generate structures from PXRD patterns.

        Args:
            pxrd:         (B, n_bins) PXRD intensity patterns
            atom_types:   (B, N) atomic numbers (fixed, known composition)
            lattice_init: (B, 3, 3) initial lattice (used for periodic distances;
                          the lattice PARAMS are generated by the model)
            mask:         (B, N) atom mask

        Returns:
            coords:       (B, N, 3) predicted fractional coordinates in [0, 1)
            lattice_params: (B, 6) predicted [a, b, c, alpha, beta, gamma]
        """
        device = pxrd.device
        B, N = atom_types.shape

        # Encode PXRD pattern once (condition doesn't change during sampling)
        pxrd_emb = self.encoder(pxrd)                          # (B, d_model)

        # Start from pure noise
        x_t = torch.randn(B, N, 3, device=device)             # coords
        l_t = torch.randn(B, 6, device=device)                 # lattice params (normalized)

        # DDIM timestep schedule: evenly spaced from 1.0 to near 0
        timesteps = torch.linspace(1.0, 1e-4, self.n_steps + 1, device=device)

        for i in range(self.n_steps):
            t_now = timesteps[i]
            t_next = timesteps[i + 1]

            # Alpha bars at current and next timestep
            ab_now = cosine_alpha_bar(t_now.unsqueeze(0))      # (1,)
            ab_next = cosine_alpha_bar(t_next.unsqueeze(0))    # (1,)

            # Broadcast t for batch
            t_batch = t_now.expand(B)

            # Reconstruct lattice matrix from current params for distance calc
            lattice_for_dist = self._params_to_approx_lattice(l_t, lattice_init)

            # Predict noise
            eps_c, eps_l = self.denoiser(
                x_t % 1.0,         # wrap coords for the network
                atom_types,
                lattice_for_dist,
                t_batch,
                pxrd_emb,
                mask,
            )

            # DDIM update for coordinates
            x_t = self._ddim_step(x_t, eps_c, ab_now, ab_next)
            x_t = x_t % 1.0       # wrap to torus

            # DDIM update for lattice params
            l_t = self._ddim_step(l_t, eps_l, ab_now, ab_next)

        # Denormalize lattice params
        if self.lat_mean is not None and self.lat_std is not None:
            lat_mean = self.lat_mean.to(device)
            lat_std = self.lat_std.to(device)
            lattice_params = l_t * lat_std + lat_mean
        else:
            lattice_params = l_t

        return x_t % 1.0, lattice_params

    def _ddim_step(self, x_t: torch.Tensor, eps: torch.Tensor,
                   ab_now: torch.Tensor, ab_next: torch.Tensor,
                   ) -> torch.Tensor:
        """Single DDIM denoising step."""
        # Reshape alpha_bars for broadcasting
        shape = [1] * (x_t.dim() - 1)
        ab_now = ab_now.view(-1, *shape)
        ab_next = ab_next.view(-1, *shape)

        # Predicted x0
        x0_pred = (x_t - (1 - ab_now).sqrt() * eps) / ab_now.sqrt().clamp(min=1e-8)

        # DDIM formula (eta=0 -> deterministic)
        sigma = self.eta * ((1 - ab_next) / (1 - ab_now) * (1 - ab_now / ab_next)).sqrt()
        dir_xt = (1 - ab_next - sigma ** 2).clamp(min=0).sqrt() * eps
        x_next = ab_next.sqrt() * x0_pred + dir_xt

        if self.eta > 0:
            x_next = x_next + sigma * torch.randn_like(x_t)

        return x_next

    def _params_to_approx_lattice(self, l_params_norm: torch.Tensor,
                                  lattice_init: torch.Tensor,
                                  ) -> torch.Tensor:
        """Use the initial lattice for distance computation during sampling.

        During early sampling steps, the lattice params are noisy garbage.
        Using them to build a lattice matrix would produce degenerate distances.
        Instead we use the initial (ground truth or average) lattice for the
        periodic distance computation, and only predict the lattice params as
        an output. This is a simplification for the Phase 1 prototype.
        """
        return lattice_init